[brain_mask]
git-tree-sha1 = "735db88b864c0c9666df58fa9cdc42cf6ec397ba"
lazy = true

    [[brain_mask.download]]
    sha256 = "6d922e5a3b17fc1f408f25e32f3540d0c56315e4e245339aa9ae3f29f9f48683"
    url = "https://github.com/StructuralEquationModels/VoxelWiseSEM.jl/releases/download/v0.1.0/brain_mask.tar.gz"

[msc_dataset]
git-tree-sha1 = "bd435353e8eb1d62f7b50ce36ea6364944c1c540"
lazy = true

    [[msc_dataset.download]]
    sha256 = "1642f95bda26a7114029402680b013c90f1584c79cd4647c917633316d88c85b"
    url = "https://github.com/StructuralEquationModels/VoxelWiseSEM.jl/releases/download/v0.1.0/msc_dataset.tar.gz"
